language: node_js
node_js:
  - 14
install:
  - npm install -g zcatalyst-cli
jobs:
  include:
    - stage: functions
      before_script:
        - cd functions/crm_crud
        - pwd
      script:
        - echo 'functions!!'
        - echo 'Installing Dependencies!'
        - npm install
      after_success:
        - echo 'deploying functions!'
        - echo ${CATALYST_TOKEN}
        - catalyst deploy --only functions --project 128000000148098 --verbose --dc eu
    - stage: client
      before_script:
        - cd client/app
        - pwd
      script:
        - echo 'client!!'
        - echo 'Installing Dependencies!'
        - npm install -- force && npm run build
        - cp ../client-package.json build/.
        - cd build
      after_success:
        - echo 'deploying client!'
        - catalyst deploy --only client --project 128000000148098 --verbose --dc eu