language: node_js
node_js:
  - 14
install:
  - npm install -g zcatalyst-cli
jobs:
  include:
    - stage: client
      before_script:
        - cd client/app
        - pwd
      script:
        - echo 'client!!'
        - echo 'Installing Dependencies!'
        - npm install -- force
        - npm run-script build
        - cp ../client-package.json build/
        - cd build
      after_success:
        - echo 'deploying client!'
        - catalyst deploy --only client --project 128000000148098 --verbose --dc eu