language: node_js
node_js:
  - 14
install:
  - npm install -g zcatalyst-cli
jobs:
  include:
    - stage: functions
      before_script:
        - cd functions/crm_crud
        - pwd
      script:
        - echo 'functions!!'
        - echo 'Installing Dependencies!'
        - npm install --force
      after_success:
        - echo 'deploying functions!'
        - catalyst deploy --only functions --project 128000000004001 --verbose --token m_1004.acf064d30dfe6bdbc160c12e838459c6.bcfee47584c00c22e8b8387218899bec
    - stage: client
      before_script:
        - cd client/app
        - pwd
      script:
        - echo 'client!!'
        - echo 'Installing Dependencies!'
        - yarn install --force
        - yarn build
        - cp ../client-package.json build/.
        - cd build
      after_success:
        - echo 'deploying client!'
        - catalyst deploy --only client --project 128000000004001 --verbose --token m_1004.acf064d30dfe6bdbc160c12e838459c6.bcfee47584c00c22e8b8387218899bec